/*
 * This source file was generated by the Gradle 'init' task
 */
package io.felipepoliveira

import io.felipepoliveira.commons.time.Cron
import kotlinx.coroutines.runBlocking
import java.time.LocalDateTime


fun main() {
    val cron = Cron.fromExpression("*/5 * * * *")
    runBlocking {
        cron.startWorker(this) {
            println("Executed at ${it.startedAt}. The next one will be at: ${it.nextExecutionAt}")
        }
    }
}
